services:
  sing-box-client:
    image: ${CLIENT_SINGBOX_IMAGE:-ghcr.io/sagernet/sing-box:1.13.12}
    container_name: sing-box-client
    restart: always
    network_mode: host
    volumes:
      - ./config:/etc/sing-box
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command: ["run", "-c", "/etc/sing-box/config.json"]

  hysteria2-client:
    image: ${CLIENT_HY2_IMAGE:-tobyxdd/hysteria:v2.9.2}
    container_name: hysteria2-client
    restart: always
    env_file: ../.env.client
    ports:
      - "${CLIENT_HY2_SOCKS5_PORT:-7891}:${CLIENT_HY2_SOCKS5_PORT:-7891}"
      - "${CLIENT_HY2_HTTP_PORT:-7892}:${CLIENT_HY2_HTTP_PORT:-7892}"
    volumes:
      - ./hy2-config:/etc/hysteria
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command: ["client", "-c", "/etc/hysteria/config.yaml"]
